[tool.black]
line-length = 80

[tool.coverage.run]
omit = [
  "**/*_test.py",
  "**/conftest.py",
]

[tool.pytest.ini_options]
addopts = """\
  --cov=. \
  --cov-branch \
  --cov-report=term-missing \
  """
