[project]
name = "ginjarator"
version = "0"
requires-python = ">=3.11"
dependencies = [
]

[project.optional-dependencies]
test = [
  "absl-py",
  "black",
  "pytest",
  "pytest-cov",
]

[tool.black]
line-length = 80

[tool.coverage.run]
omit = [
  "**/*_test.py",
  "**/conftest.py",
]

[tool.pytest.ini_options]
addopts = """\
  --cov=. \
  --cov-branch \
  --cov-report=term-missing \
  """
